# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36506b804b03ee91b3d2016a0103c6f64e1dc53aa288d91482a7e30054fcfab5ba1e1b1759f3ff90f537b0e20aa25a5028e657cf0d585b57692c0b99791ebd45

test:
  secret_key_base: 8fdd8b3b0a7b9b45b5467356ef81dd0028bfd7f0060d00cae990d50498c93bb0090ed7995cb089d908e1b6e95da8573cd51583772988c40aeac0b5a9e555dc9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
